name: Autoupdate branches on changes to master
on:
  push:
    branches: [master]
  pull_request:
    types: [unlabeled]
  workflow_dispatch:

jobs:
  autoupdate-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install npm packages
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_PACKAGES_TOKEN }}
          npm config set @trilogy-group:registry https://npm.pkg.github.com
          
          rm -f ./package.json ./package-lock.json
          npm i @trilogy-group/lambda-process@latest
      - name: autoupdate branches
        uses: actions/github-script@v4
        env:
          LAMBDA_TOKEN: ${{secrets.LAMBDA_TOKEN}}
        with:
          script: |
            const autoupdateBranches = require("@trilogy-group/lambda-process/autoupdateBranches");
            const { owner, repo } = context.repo;
            const autoupdateBranchesResult = await autoupdateBranches.check(process.env.LAMBDA_TOKEN, owner, repo, 'master');
            console.info(autoupdateBranchesResult.info);